### ISSUE TITLE
`input text` 新增特性 

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/infinite#22]
- [x] 新增默认值, 如果直接回车就使用该默认值,  通过改造 `placeholder` 这个字段, 这个名称可能也要变
- [x] 新增 `required` , 为 `true` 则必须要填写, 并附带一句错误信息, 为 `false` 则直接使用默认值
- [x] 新增 `required msg`, 当 `required` 为 `true` 时有效

**Comment by fzdwx** [comment]
@whatwewant  是否还有遗漏。

**Comment by whatwewant** [comment]
很赞，完整，暂时没有其他需求
