### ISSUE TITLE
readme文档中链接访问出错，例如： https://fzdwx.github.io/infinite/zh/guide/getting-started

### ISSUE THREAD

**Issue by aozeahj** [fzdwx/infinite#30]

**Comment by fzdwx** [comment]
好了，你再试试。

**Comment by fzdwx** [comment]
没什么问题就先 close 了。

**Comment by aozeahj** [comment]
好像又不行了

**Comment by fzdwx** [comment]
我刚刚试了， 是可以的。

![2022-10-10_21-22](https://user-images.githubusercontent.com/65269574/194876327-d9e57240-516f-4350-86c2-ff8dacc91f28.png)
