### ISSUE TITLE
input 组件能不能实现类似linux的实现点击键盘向上按钮查看历史输入的功能

### ISSUE THREAD

**Issue by ljhhhhhh1224** [fzdwx/infinite#34]

**Comment by fzdwx** [comment]
可以。

1. 这个文件保存在哪，需要持久化吗
2. 是否默认开启
3. ..

细节需要讨论

**Comment by fzdwx** [comment]
go 里面也有 readline 的实现: https://github.com/chzyer/readline

**Comment by ljhhhhhh1224** [comment]
> go 里面也有 readline 的实现: https://github.com/chzyer/readline

感谢,这个库可以满足我的需求！
