### ISSUE TITLE
text.WithPrompt 的字符串为什么不显示？

### ISSUE THREAD

**Issue by J1nAB1n9** [fzdwx/infinite#35]
![QQ图片20221102105559](https://user-images.githubusercontent.com/42513580/199384750-d3f930f6-8872-45f5-91d2-3d85ee429c15.png)
![QQ图片20221102105636](https://user-images.githubusercontent.com/42513580/199384764-d3078c1a-9680-4e25-ac6b-06e0065e4fd6.png)

**Comment by fzdwx** [comment]
图片看不到

**Comment by J1nAB1n9** [comment]
大佬再看看，"what's your name?"没有显示在input前面

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/199385554-2db861dd-1fc0-4929-8382-4a4a15d601d7.png)

我这边是好的

**Comment by J1nAB1n9** [comment]
似乎还是不行

**Comment by J1nAB1n9** [comment]
似乎还是不行
______________________________________________
会是go版本或者windows的问题吗

![image](https://user-images.githubusercontent.com/42513580/199386567-28e4794e-2dc7-4bfb-93c5-19bbde36d603.png)

**Comment by fzdwx** [comment]
你是直接作为依赖用的是吧

**Comment by J1nAB1n9** [comment]
对

**Comment by fzdwx** [comment]
我 release 一下，你等等在试。
