### ISSUE TITLE
多选时增加方向键的一些控制

### ISSUE THREAD

**Issue by wangzhiy** [fzdwx/infinite#38]
多选时：

1. 如果将choice改为空格键，则tab和方向左右键会回到第一个选项，建议去掉
- [x] 增加pgup pgon键翻页功能 https://github.com/fzdwx/infinite/commit/a0d633085e606cc097bc4f095a637eb72f96288e
- [x] 增加左右键全选/取消功能 https://github.com/fzdwx/infinite/commit/0acad7a677ea5d70be57c99003a7bc5784aa8eb6

方向键的控制应该会依赖github.com/charmbracelet/bubbles

**Comment by fzdwx** [comment]
pr? thanks

**Comment by fzdwx** [comment]
selection page 已经完成了
