### ISSUE TITLE
请问后续会支持简单的ansi输出吗

### ISSUE THREAD

**Issue by yqchilde** [fzdwx/infinite#42]
先感谢作者的这个项目👍🏻

描述可能不太准，就是ansi输出一句话，带符号，比如下图，

`fmt.Println("√ 服务器启动成功!")` 如果`√` 符号可以按照正常的ansi颜色输出就更好了，比如不用fmt，用包里的Print

![image](https://user-images.githubusercontent.com/36953759/233254698-af2ce7eb-b310-408c-8089-79c975ec2345.png)

**Comment by yqchilde** [comment]
抱歉，没事了，我直接写ansi码吧

**Comment by fzdwx** [comment]
可以啊， 用 style 就行

**Comment by yqchilde** [comment]
> 可以啊， 用 style 就行
> 
> `style.bg`

感谢回复，刚用了`style.New().Fg(color.Green).Render("√")`解决了👍🏻

**Comment by fzdwx** [comment]
好的，欢迎 PR 你想要的功能或者代码上的优化！
