### ISSUE TITLE
Win7 环境下无法使用

### ISSUE THREAD

**Issue by Zccf** [fzdwx/infinite#45]
在win7环境下无法使用，控制台返回错误信息：?[?25l  (就是这个报错信息，我也不知道为啥)
go版本1.20.6  和 1.19.11 都无法使用。

**Comment by fzdwx** [comment]
运行的 demo 程序有吗？

**Comment by Zccf** [comment]
您好，我使用的Demo如下（官网提供demo）：
`package main

import (
	"fmt"
	inf "github.com/fzdwx/infinite"
	"github.com/fzdwx/infinite/components/selection/confirm"
)

func main() {

	val, _ := inf.NewConfirmWithSelection(
		confirm.WithDefaultYes(),
	).Display()

	if val {
		fmt.Println("yes, you are.")
	} else {
		fmt.Println("no,you are not.")
	}
}
`

出现的现象：go run .  执行后，程序立即结束，控制台输出内容为： ?[?25lno,you are not.

**Comment by Zccf** [comment]
如果您暂时没有win7环境的话，您可以远程我的电脑进行操作。🤝

**Comment by fzdwx** [comment]
我在 win11 上试了一下，是可以的。win7 的话可能确实有点问题，如果您有能力 debug 的话，可以尝试看看是哪个地方有问题。

**Comment by Zccf** [comment]
您好，我刚刚Debug了一下，我对Debug操作并不是很熟练，不过我获得了如下错误信息：
在您源代码 confirm.go 文件中 第90行 （ _,err:=c.startUp.Run()  ）发现了如下错误信息：
prepare console: set console mode: The parameter is incorrect.
golang.org/x/sys/windows.ERROR_INVALID_PARAMETER (87)

我不确定这些信息对你有价值。

**Comment by Zccf** [comment]
错误追溯流程：
1. github.com\fzdwx\infinite@v0.12.1\components\startup.go     **36行**
2. github.com\charmbracelet\bubbletea@v0.24.2\tea.go     **491行**
3. github.com\charmbracelet\bubbletea@v0.24.2\tty.go    **60行**
4. github.com\muesli\cancelreader@v0.2.2\cancelreader_windows.go    **33行**

最终错误锁定在了 第四步的库中，错误信息  
`prepare console: set console mode: The parameter is incorrect.
golang.org/x/sys/windows.ERROR_INVALID_PARAMETER (87)`

继续深入的话，就到了go基本库了

**Comment by fzdwx** [comment]
收到

**Comment by fzdwx** [comment]
看您给的报错信息的代码应该是跟 cancelreader 这个库有关 

https://github.com/charmbracelet/bubbletea/blob/c4c83ba757f891a8fbe513790b0176f9f26fc85b/tty.go#L60
https://github.com/muesli/cancelreader/blob/245609eb8557cff32c56eed62b04a2d096c83e83/cancelreader_windows.go#L33

**Comment by Zccf** [comment]
您好，请问这个有没有解决办法呢？

**Comment by fzdwx** [comment]
你可以 fork 这两个仓库以及当前仓库，然后改 https://github.com/muesli/cancelreader/blob/245609eb8557cff32c56eed62b04a2d096c83e83/cancelreader_windows.go#L33 这行调用 windows api 的代码

**Comment by Zccf** [comment]
请问应该改成什么呢？我不太会。😨

**Comment by fzdwx** [comment]
我也不会

**Comment by Zccf** [comment]
😭😨😳😥🙃😥😷😞😭😭😣😣😥😨😭😪😥😰😗😱😳😪😭😭😭😭😭😭😭
