### ISSUE TITLE
是否有类似于placeholder的组件来实现输入提示

### ISSUE THREAD

**Issue by alice92bob** [fzdwx/infinite#47]
我尝试使用withdefaultvalue来当做placeholder，但是如果不进行输入 使用command+c进行程序退出，会默认传递defaultvalue
目前是强制在我使用的过程中增加了退出触发键，但是这无法保证其他使用我程序的人也是用退出触发键

**Comment by fzdwx** [comment]
OK, 我添加了一个新的选项 `text.WithDefaultValueRequireValue(false),`

**Comment by fzdwx** [comment]
https://github.com/fzdwx/infinite/commit/2c82824929f15154da743eb7947ab21df5ed11dc#diff-669dec87e33cf751ac7fbc10345acf6afc80ce51a32fdd9d7592671503570e3dR17
