### ISSUE TITLE
在使用idea的code with me 远程编程的时候,直接的控制台会输出异常

### ISSUE THREAD

**Issue by alice92bob** [fzdwx/infinite#48]
![image](https://github.com/fzdwx/infinite/assets/128616404/0503eb26-cc76-4477-bc80-30ed5cab85ed)

2727/2828/2222\::2727/2828/2222\]10;rg:2727/2828/2222\]11;rg:2727/2828/2222\]11;rg:2727/2828/2222\]11;rg:2727/2828/2222\]11;rg:2727/2828/2222\]11;rg]11;rg//\]11;rg

更换不同的code with me主题会出现不同的输出

在默认终端下能够正常运行

**Comment by fzdwx** [comment]
![image](https://github.com/fzdwx/infinite/assets/65269574/68bae291-7d21-42ca-843d-507b2b3ecd12)


我这边没问题，我是发起方，您那边是什么环境？

**Comment by alice92bob** [comment]
我是公司内网使用一台mac作为转发端，家里使用windows 作为回家coding的机器，mac端开启code with me 在windows端加入，这种情况下，会从golang的终端变成code with me 的终端，此时使用mac端code with me 内置的终端中的展示会出现bug，使用iterm2这类的外置终端也不会出现问题，基本判断问题在code with me 

https://github.com/fzdwx/infinite/assets/128616404/11fb3ad5-6348-423b-a12d-9c7446f6fb27

**Comment by fzdwx** [comment]
看起来是用了 `code with me` 的共享终端会出现这个问题

**Comment by fzdwx** [comment]
你把 filter input 这个的样式都设置为 `style.new()` 试试，也就是用默认的样式

**Comment by qianzyGit** [comment]
尝试了无变化，感觉像是tty终端的什么分隔符之类的bug了

**Comment by alice92bob** [comment]
尝试了无变化，感觉像是tty终端的什么分隔符之类的bug了
