### ISSUE TITLE
Q: 我该如何重写实现一个KeyMap中的Back功能，来实现不同菜单中的跳转

### ISSUE THREAD

**Issue by alice92bob** [fzdwx/infinite#49]
我在尝试做一个程序拥有多级选择针对不同的功能组件，所以涉及1级2级菜单的跳转，这个能基于keyMap增加一个back选项来实现菜单跳转嘛，读了几遍文档和example 感觉没太弄明白，麻烦了大佬了

**Comment by qwe7002** [comment]
我是直接在菜單中加了個Back指令，通過返回-1跳出當前循環的方法來實現返回上一級
